In [5]:
import torch
import numpy as np
import torch.nn as nn

In [9]:
ip = torch.rand(1, 3, 8, 8)

In [20]:
ip

tensor([[[[6.2314e-01, 8.0240e-01, 4.7124e-01, 6.5051e-01, 6.7218e-01,
           8.3777e-01, 9.9957e-01, 6.8970e-01],
          [1.8900e-01, 8.8953e-01, 5.5241e-01, 4.1432e-01, 7.3587e-01,
           1.6462e-02, 4.8116e-01, 8.3806e-01],
          [4.0610e-01, 8.6350e-01, 8.8055e-01, 7.0699e-01, 9.2734e-01,
           1.2733e-01, 5.9023e-02, 8.9622e-01],
          [7.6677e-01, 7.3377e-01, 7.0055e-01, 7.2580e-01, 5.5095e-01,
           6.4664e-01, 6.1911e-01, 8.5382e-01],
          [2.5940e-01, 5.6686e-01, 8.3781e-01, 3.7163e-01, 1.5323e-01,
           7.5034e-01, 5.6323e-01, 6.4323e-02],
          [1.8301e-01, 6.3449e-01, 8.8737e-01, 4.1911e-01, 7.4487e-01,
           9.3982e-01, 6.9918e-01, 2.3154e-01],
          [7.1038e-01, 7.7502e-01, 7.0484e-01, 8.1576e-01, 7.9992e-02,
           3.8118e-01, 3.1045e-01, 9.3720e-01],
          [9.9165e-01, 1.5181e-01, 9.3442e-01, 6.8309e-02, 3.5386e-01,
           9.6946e-01, 7.5498e-01, 3.4382e-01]],

         [[3.7118e-01, 8.2773e-01, 2.4151e-01,

In [10]:
global_pooling = nn.AdaptiveAvgPool2d(1)

In [26]:
x = global_pooling(ip)

In [36]:
print(x.shape)
print(x)

torch.Size([1, 3, 1, 1])
tensor([[[[0.5925]],

         [[0.5135]],

         [[0.4720]]]])


In [37]:
linear = nn.Linear(1, 10)

In [38]:
linear(x)

tensor([[[[-1.2038, -0.8793, -1.0033,  0.6072, -0.0846,  0.2695,  0.1646,
           -0.4958, -1.1404,  0.0263]],

         [[-1.1271, -0.8750, -0.9562,  0.6061, -0.1214,  0.2196,  0.1216,
           -0.5600, -1.1014, -0.0424]],

         [[-1.0868, -0.8727, -0.9315,  0.6055, -0.1408,  0.1934,  0.0990,
           -0.5937, -1.0809, -0.0785]]]], grad_fn=<AddBackward0>)