In [1]:
import os
import sys
import time
import glob
import numpy as np
import logging
import argparse
import tensorflow as tf
import numpy as np
import utils
from tqdm import tqdm
import shutil
from model_search import Network
from architect_graph import Architect

In [2]:
import utils
from genotypes import Genotype
# tf.enable_eager_execution()
tf.set_random_seed(6969)
np.random.seed(6969)

In [3]:
# tf.enable_eager_execution()

In [4]:
args = {
    "momentum": 0.9,
    "weight_decay": 3e-4,
    "arch_learning_rate": 3e-1,
    "momentum": 0.9,
    "grad_clip": 5,
    "learning_rate": 0.025,
    "learning_rate_decay": 0.97,
    "learning_rate_min": 0.0001,
    "num_batches_per_epoch": 2000,
    
    "unrolled": True,
    "epochs": 10,
    "train_batch_size": 8,
    "batch_size": 8,
    "eval_batch_size": 8,
    "save": "EXP",
    "init_channels": 3,
    "num_layers": 3,
    "num_classes": 6,
    "crop_size": [8, 8],
    "save_checkpoints_steps": 100,
    "model_dir": 'gs://unet-darts/train-search-ckptss',
    "max_steps": 10000,
    # NEW
    "steps_per_eval": 2,
    "num_train_examples": 16,
    "num_batches_per_epoch": 2,
    
    "seed": 6969,
    #
    
    "use_tpu": False,
    "use_host_call": False,
    "tpu": 'unet-darts',
#     "zone": 'us-central1-f',
#     "project": "isro-nas"
    "zone": None,
    "project": None
}

class Struct:
    def __init__(self, **entries):
        self.__dict__.update(entries)

args = Struct(**args)

### input_fn

In [5]:
def make_inp_fn(filename, mode, batch_size):
    
    def _input_fn():
        image_dataset = tf.data.TFRecordDataset(filename)
        W, H = 16, 16

        # Create a dictionary describing the features.  
        image_feature_description = {
            'name': tf.FixedLenFeature([], tf.string),  
            'label_encoded': tf.FixedLenFeature([], tf.string),
            'encoded': tf.FixedLenFeature([], tf.string)
        }
        def _parse_image_function(example_proto):
            # Parse the input tf.Example proto using the dictionary above.
            feature= tf.parse_single_example(example_proto, image_feature_description)
            image= feature['encoded']
            label = feature['label_encoded']
            name = feature['name']

            image = tf.image.decode_png(image, channels=3)
            label = tf.image.decode_png(label, channels=3)

            image = tf.cast(image, tf.float32)
            image = tf.image.resize(image, (W, H))
            label = tf.cast(label, tf.float32)
            label = tf.image.resize(label, (W, H))

            return image, label

        dataset = image_dataset.map(_parse_image_function)
        
        if mode == tf.estimator.ModeKeys.TRAIN:
            num_epochs = None # indefinitely
            dataset = dataset.shuffle(buffer_size = 10 * batch_size)
        else:
            num_epochs = 1 # end-of-input after this

        dataset = dataset.repeat(num_epochs).batch(batch_size)

        return dataset
    
    return _input_fn

In [6]:
def make_inp_fn2(filename, mode, batch_size):
    
    def _input_fn(params):
        W, H = args.crop_size[0], args.crop_size[1]
        NUM_IMAGES = 20
        x_train = np.random.randint(0, 256, (NUM_IMAGES, W, H, 3)).astype(np.float32)
        y_train = np.random.randint(0, args.num_classes, (NUM_IMAGES, W, H, 1)).astype(np.float32)
        x_valid = np.random.randint(0, 256, (NUM_IMAGES, W, H, 3)).astype(np.float32)
        y_valid = np.random.randint(0, args.num_classes, (NUM_IMAGES, W, H, 1)).astype(np.float32)

        ds = (x_train, x_valid), (y_train, y_valid)
        dataset = tf.data.Dataset.from_tensor_slices(ds)
        num_epochs = None # indefinitely
        dataset = dataset.shuffle(buffer_size = 10 * batch_size)

        dataset = dataset.repeat(num_epochs).batch(batch_size, drop_remainder=True)
        return dataset
    
    return _input_fn

### Model function

In [7]:
class GeneSaver(tf.estimator.SessionRunHook):
    def __init__(self, genotype):
        self.genotype = genotype
    
    def begin(self):
        self.global_step = tf.train.get_or_create_global_step()
    
    def end(self, session):
        normal_gene_op = self.genotype.normal
        reduce_gene_op = self.genotype.reduce
        
        self.global_step = session.run(self.global_step)
        normal_gene = session.run(normal_gene_op)
        reduce_gene = session.run(reduce_gene_op)
        
        genotype = Genotype(
            normal=normal_gene, normal_concat=self.genotype.normal_concat,
            reduce=reduce_gene, reduce_concat=self.genotype.reduce_concat
        )
        
        filename = 'final_genotype.{}'.format((self.global_step))
        tf.logging.info("Saving Genotype for step: {}".format(str(self.global_step)))
        utils.write_genotype(genotype, filename)

In [8]:
def model_fn(features, labels, mode):
    criterion = tf.losses.softmax_cross_entropy
    model = Network(C=args.init_channels, net_layers=args.num_layers, criterion=criterion, num_classes=args.num_classes)
    
    global_step = tf.train.get_global_step()
    learning_rate_min = tf.constant(args.learning_rate_min)
    
    learning_rate = tf.train.exponential_decay(
        args.learning_rate,
        global_step,
        decay_rate=args.learning_rate_decay,
        decay_steps=args.num_batches_per_epoch,
        staircase=True,
    )
    
    lr = tf.maximum(learning_rate, learning_rate_min)
    tf.summary.scalar('learning_rate', lr)
    
    optimizer = tf.train.MomentumOptimizer(lr, args.momentum)
    criterion = tf.losses.sigmoid_cross_entropy
    
    eval_hooks = None
    
    loss = None
    train_op = None
    eval_metric_ops = None
    prediction_dict = None
    export_outputs = None
    # 2. Loss function, training/eval ops
    if mode == tf.estimator.ModeKeys.TRAIN:
        (x_train, x_valid) = features
        (y_train, y_valid) = labels

        preds = model(x_train)
        architect = Architect(model, args)
        architect_step = architect.step(input_train=x_train,
                                       target_train=y_train,
                                       input_valid=x_valid,
                                       target_valid=y_valid,
                                       unrolled=args.unrolled,
                                       )


        with tf.control_dependencies([architect_step]):
            w_var = model.get_thetas()
            loss = model._loss(preds, y_train)
            grads = tf.gradients(loss, w_var)
            train_op = optimizer.apply_gradients(zip(grads, w_var), global_step=tf.train.get_global_step())

#         miou = tf.metrics.mean_iou(
#                     labels=y_train,
#                     predictions=preds,
#                     num_classes=args.num_classes
#                 )
#         acc = tf.metrics.accuracy(labels=y_train, 
#                                   predictions=preds)
#         eval_metric_ops = {
#             "miou": miou,
#             "accuracy": acc
#         }
    
    elif mode == tf.estimator.ModeKeys.EVAL:
#         global_step = tf.train.get_global_step()
        genotype = model.genotype()
        gene_saver = GeneSaver(genotype)
        eval_hooks = [gene_saver]
        
        (x_train, x_valid) = features
        (y_train, y_valid) = labels
        preds = model(x_valid)
        loss = model._loss(preds, y_valid)
        miou = tf.metrics.mean_iou(
                    labels=y_valid,
                    predictions=preds,
                    num_classes=args.num_classes
                )
        acc = tf.metrics.accuracy(labels=y_valid, predictions=preds)
        eval_metric_ops = {
            "miou": miou,
            "accuracy": acc
        }
        
    elif mode == tf.estimator.ModeKeys.PREDICT:
        x = features
        y = labels
        preds = model(x)
        prediction_dict = {"predictions": preds}
        export_outputs = {"predict_export_outputs": tf.estimator.export.PredictOutput(outputs = preds)}
    
    # 5. Return EstimatorSpec
    return tf.estimator.EstimatorSpec(
        mode = mode,
        predictions = prediction_dict,
        loss = loss,
        train_op = train_op,
        eval_metric_ops = eval_metric_ops,
        export_outputs = export_outputs,
        evaluation_hooks=eval_hooks
    )

### Estimator

In [9]:
# Create functions to read in respective datasets
def get_train():
    return make_inp_fn2(filename = '../../datasets/infer/infer-00000-00007.tfrecords',
                        mode = tf.estimator.ModeKeys.TRAIN,
                        batch_size = args.batch_size)

In [10]:
# Create serving input function
def serving_input_fn():
    feature_placeholders = {
      IMAGE_LOC: tf.placeholder(tf.float32, [None])
    }
    
    feature_placeholders['IMAGES'] = tf.placeholder(tf.float32, [None, args.crop_size[0], args.crop_size[1], args.init_channels])
    
    features = {
    key: tf.expand_dims(tensor, -1)
    for key, tensor in feature_placeholders.items()
    }

    return tf.estimator.export.ServingInputReceiver(features, feature_placeholders)


In [11]:
config = tf.estimator.RunConfig(save_checkpoints_steps=args.save_checkpoints_steps,
                                model_dir=args.model_dir, tf_random_seed=args.seed)

In [12]:
# Create custom estimator's train and evaluate function
def train_and_evaluate(output_dir):
    estimator = tf.estimator.Estimator(model_fn = model_fn, 
                         config=config)
    train_spec = tf.estimator.TrainSpec(input_fn = get_train(),
                                    max_steps = 1000)
    exporter = tf.estimator.LatestExporter('exporter', serving_input_fn)
    eval_spec = tf.estimator.EvalSpec(input_fn = get_train(),
                                  steps = None, throttle_secs=600)
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)

In [13]:
estimator = tf.estimator.Estimator(model_fn = model_fn, 
                     config=config)
estimator.train(input_fn = get_train(), steps = 5)

INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb2dd7e0510>, '_model_dir': 'gs://unet-darts/train-search-ckptss', '_protocol': None, '_save_checkpoints_steps': 100, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': 6969, '_save_summary_steps': 100, '_device_fn': None, '_session_creation_timeout_secs': 7200, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_experimental_max_worker_delay_secs': None, '_evaluation_master': '', '_eval_distribute': None, '_global_id_in_cluster': 0, '_master': ''}
Instructions for updating:
Use Variable.read_value. Variables in 2.X are in

In [14]:
estimator.get_variable_value('network/sequential/conv2d/kernel:0')[0]
# [-0.1213921 , -0.05426454, -0.12348816,  0.14683837
# rray([[[-2.79849414e-02,  1.16353922e-01, -2.07804427e-01,

array([[[ 0.21160507, -0.21848902,  0.23653212,  0.11754844,
          0.07842084,  0.20762058, -0.02427896,  0.05266505,
          0.06588185],
        [-0.10964472, -0.19849841,  0.20948522, -0.08818717,
         -0.1918711 ,  0.14931907, -0.10729859, -0.17201567,
         -0.11432522],
        [-0.12347911,  0.16643406, -0.05902734, -0.03249671,
          0.11748508,  0.14278087, -0.05715536,  0.21601404,
         -0.22197345]],

       [[-0.19773257,  0.21238694, -0.08473241,  0.08368283,
         -0.11171204, -0.11749534, -0.12242602, -0.14338504,
         -0.21754499],
        [ 0.11206506, -0.10706716,  0.08288258,  0.09993035,
          0.04749881,  0.07117351,  0.05172399, -0.18064596,
         -0.08402789],
        [-0.11511762,  0.21876034,  0.06738853,  0.0756783 ,
          0.12194356, -0.16608292,  0.0934642 ,  0.01872056,
         -0.22174531]],

       [[ 0.22120355, -0.08398765, -0.07401478,  0.13258912,
         -0.20800927,  0.12645443, -0.06177693, -0.21864271,
    

In [15]:
estimator.get_variable_value('network/alphas_normal')
# [[1.20727425e-04, 4.81855881e-04, 2.67096650e-04, 5.32005564e-04],
# array([[ 0.52086633, -0.42027888,  0.1691421 ,  0.5943173 ],

array([[ 0.01695889, -0.04184179, -0.01425209,  0.04107325],
       [-0.04151864,  0.00794181,  0.08955112, -0.05951698],
       [ 0.02892872, -0.04694319, -0.01564714,  0.03687111],
       [-0.00940474, -0.00713697,  0.04399676, -0.02644248],
       [ 0.00102057, -0.03073446, -0.02404075,  0.05464585],
       [ 0.02468788,  0.0012726 , -0.045113  ,  0.0225525 ],
       [ 0.01003213, -0.00243887, -0.05038981,  0.04622243],
       [ 0.01834823, -0.01843441, -0.02245464,  0.02499198],
       [ 0.02915651, -0.02340005, -0.02678607,  0.02285247],
       [ 0.01329712, -0.00685036, -0.02164326,  0.01748462],
       [-0.02285887,  0.0109119 ,  0.02861176, -0.01453894],
       [-0.00064974,  0.00058517,  0.00407862, -0.00187617],
       [-0.0025976 ,  0.00103705,  0.00718386, -0.00399489],
       [-0.00473083,  0.00820372,  0.01349145, -0.01548955]],
      dtype=float32)

In [11]:
train_and_evaluate(args.model_dir)

INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fbe35be9250>, '_model_dir': './outputdir', '_protocol': None, '_save_checkpoints_steps': 100, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_session_creation_timeout_secs': 7200, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_experimental_max_worker_delay_secs': None, '_evaluation_master': '', '_eval_distribute': None, '_global_id_in_cluster': 0, '_master': ''}
INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation l

## Extra Test

In [5]:
criterion = tf.losses.sigmoid_cross_entropy
model = Network(C=args.init_channels, net_layers=args.num_layers, criterion=criterion, num_classes=args.num_classes)

In [6]:
(x_train, x_valid), (y_train, y_valid) = get_train()().make_one_shot_iterator().get_next()

Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.


In [7]:
logits = model(x_train)


Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


<tf.Tensor 'IteratorGetNext:2' shape=(4, 4, 4, 1) dtype=float32>

In [10]:
miou = tf.metrics.mean_iou(
    labels=y_train,
    predictions=logits,
    num_classes=args.num_classes
)

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


In [11]:
global_init_op = tf.global_variables_initializer()
local_init_op = tf.local_variables_initializer()

In [14]:
with tf.Session() as sess:
    sess.run([global_init_op, local_init_op])
    pred = sess.run(logits)
    miou_out = sess.run(miou)

In [15]:
pred

array([[[[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]]],


       [[[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]]],


       [[[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]]],


       [[[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.],
         [3.]]]], d

In [16]:
tf.Session().run(y_train)

array([[[[3.],
         [3.],
         [0.],
         [4.]],

        [[5.],
         [1.],
         [3.],
         [1.]],

        [[0.],
         [1.],
         [1.],
         [4.]],

        [[0.],
         [1.],
         [0.],
         [1.]]],


       [[[0.],
         [3.],
         [2.],
         [0.]],

        [[1.],
         [0.],
         [2.],
         [2.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [4.],
         [4.]]],


       [[[2.],
         [2.],
         [5.],
         [5.]],

        [[4.],
         [0.],
         [0.],
         [5.]],

        [[1.],
         [2.],
         [4.],
         [0.]],

        [[4.],
         [5.],
         [2.],
         [1.]]],


       [[[2.],
         [1.],
         [2.],
         [5.]],

        [[2.],
         [3.],
         [4.],
         [0.]],

        [[1.],
         [0.],
         [3.],
         [0.]],

        [[5.],
         [2.],
         [2.],
         [3.]]]], d

In [17]:
miou_out

(0.0, array([[ 0.,  0.,  0., 11.,  0.,  0.],
        [ 0.,  0.,  0., 14.,  0.,  0.],
        [ 0.,  0.,  0.,  8.,  0.,  0.],
        [ 0.,  0.,  0., 12.,  0.,  0.],
        [ 0.,  0.,  0., 11.,  0.,  0.],
        [ 0.,  0.,  0.,  8.,  0.,  0.]]))