In [9]:
import tensorflow as tf
import numpy as np

In [3]:
x = tf.placeholder(tf.float32)

In [4]:
y =  2*x*x

In [5]:
var_grad = tf.gradients(y, x)

In [14]:
with tf.Session() as sess:
    xs = np.random.randint(0, 255, (5, 3))
    var_grad_val = sess.run(var_grad,feed_dict={x: xs}) 
    print(xs, var_grad_val)
    print(xs.shape, var_grad_val)

[[198 130 157]
 [165  23 245]
 [  6 106 107]
 [224  70   3]
 [  9 181 107]] [array([[792., 520., 628.],
       [660.,  92., 980.],
       [ 24., 424., 428.],
       [896., 280.,  12.],
       [ 36., 724., 428.]], dtype=float32)]
(5, 3) [array([[792., 520., 628.],
       [660.,  92., 980.],
       [ 24., 424., 428.],
       [896., 280.,  12.],
       [ 36., 724., 428.]], dtype=float32)]
